apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-dynamodb-access
      containers:
        - name: backend
          image: 960293440626.dkr.ecr.ap-northeast-1.amazonaws.com/k8s-gamo-backend:kawauso
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-1
            - name: DYNAMODB_TABLE_NAME
              value: k8s-gamo
