apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingpong
  labels:
    app: pingpong
spec:
  schedule: "10 12 * * *" # 1 Cron記法でスケジュールを定義
  timezone: Asia/Tokyo
  suspend: false
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate: # 2 Jobリソースのテンプレート
    spec:
      template:
        metadata:
          labels:
            app: pingpong
        spec:
          containers:
            - name: pingpong
              image: ubuntu:23.10
              command:
                - "sh"
                - "-c"
                - |
                  echo [`date`] ping!
                  sleep 10
                  echo [`date`] pong!
          restartPolicy: OnFailure
